# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wHnMhdJldIfWMIcT8OHcIfWMYq3_TXPc
"""

import pandas as pd

data = {
    'termino': ['Estadistica', 'datos', 'Tema de conjuntos', 'Axiomas', 'Eventos', 'probabilidad'],
    '¿Que se?': ['Es el estudio de la variabilidad','conjunto que es infomacion','vario temas a expresar','familias que pretenecen a mas familias','situaciones que pasan ','algo que podria pasar'],
    '¿que deseo aprender?':['poder saber como poder usarlas', 'saber identificarlo y evaluarlos', 'poder saber mas temas', 'a que pertenece cada cosa', 'diferenciarlos', 'saber el como y poder calcularlo'],
    '¿que aprendí?': [""] * 6
}

tabla = pd.DataFrame(data)

# Ask the user if they want to fill in the "¿que aprendí?" column
fill_aprendi = input("¿Desea llenar la columna '¿que aprendí?' ahora? (si/no): ").lower()

if fill_aprendi == "si":
    for index in range(len(tabla)):
        # Prompt the user for each row
        aprendizaje = input(f"¿Qué aprendió sobre '{tabla['termino'][index]}'? ")
        tabla.loc[index, '¿que aprendí?'] = aprendizaje

print(tabla)

"""problematica con el software


*   Lento.
*   quejas por comentarios.
posible solucion:
aumentar el rendimiento y rapidez del software.


"""